# TCL File Generated by Component Editor 17.0
# Sun Apr 03 13:27:08 EEST 2022
# DO NOT MODIFY


# 
# serv_uart "serv_uart" v2.0
#  2022.04.03.13:27:08
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module serv_uart
# 
set_module_property DESCRIPTION ""
set_module_property NAME serv_uart
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME serv_uart
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL subservient_wrapped_av_wrapped
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ff_ram.v VERILOG PATH ip/serv_uart/rtl/ff_ram.v
add_fileset_file serv_alu.v VERILOG PATH ip/serv_uart/rtl/serv_alu.v
add_fileset_file serv_bufreg.v VERILOG PATH ip/serv_uart/rtl/serv_bufreg.v
add_fileset_file serv_con.v VERILOG PATH ip/serv_uart/rtl/serv_con.v
add_fileset_file serv_csr.v VERILOG PATH ip/serv_uart/rtl/serv_csr.v
add_fileset_file serv_ctrl.v VERILOG PATH ip/serv_uart/rtl/serv_ctrl.v
add_fileset_file serv_decode.v VERILOG PATH ip/serv_uart/rtl/serv_decode.v
add_fileset_file serv_immdec.v VERILOG PATH ip/serv_uart/rtl/serv_immdec.v
add_fileset_file serv_mem_if.v VERILOG PATH ip/serv_uart/rtl/serv_mem_if.v
add_fileset_file serv_rf_if.v VERILOG PATH ip/serv_uart/rtl/serv_rf_if.v
add_fileset_file serv_rf_ram.v VERILOG PATH ip/serv_uart/rtl/serv_rf_ram.v
add_fileset_file serv_rf_ram_if.v VERILOG PATH ip/serv_uart/rtl/serv_rf_ram_if.v
add_fileset_file serv_rf_top.v VERILOG PATH ip/serv_uart/rtl/serv_rf_top.v
add_fileset_file serv_state.v VERILOG PATH ip/serv_uart/rtl/serv_state.v
add_fileset_file serv_top.v VERILOG PATH ip/serv_uart/rtl/serv_top.v
add_fileset_file servant_timer.v VERILOG PATH ip/serv_uart/rtl/servant_timer.v
add_fileset_file serving.v VERILOG PATH ip/serv_uart/rtl/serving.v
add_fileset_file serving_arbiter.v VERILOG PATH ip/serv_uart/rtl/serving_arbiter.v
add_fileset_file serving_mux.v VERILOG PATH ip/serv_uart/rtl/serving_mux.v
add_fileset_file serving_ram.v VERILOG PATH ip/serv_uart/rtl/serving_ram.v
add_fileset_file subservient.v VERILOG PATH ip/serv_uart/rtl/subservient.v
add_fileset_file subservient_core.v VERILOG PATH ip/serv_uart/rtl/subservient_core.v
add_fileset_file subservient_debug_switch.v VERILOG PATH ip/serv_uart/rtl/subservient_debug_switch.v
add_fileset_file subservient_ram.v VERILOG PATH ip/serv_uart/rtl/subservient_ram.v
add_fileset_file subservient_rf_ram_if.v VERILOG PATH ip/serv_uart/rtl/subservient_rf_ram_if.v
add_fileset_file subservient_wrapped.v VERILOG PATH ip/serv_uart/rtl/subservient_wrapped.v
add_fileset_file subservient_wrapped_av_wrapped.v VERILOG PATH ip/serv_uart/rtl/subservient_wrapped_av_wrapped.v TOP_LEVEL_FILE
add_fileset_file uart.v VERILOG PATH ip/serv_uart/rtl/uart.v
add_fileset_file uart_rx.v VERILOG PATH ip/serv_uart/rtl/uart_rx.v
add_fileset_file uart_tx.v VERILOG PATH ip/serv_uart/rtl/uart_tx.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 readdatavalid readdatavalid Output 1
add_interface_port avalon_slave_0 address address Input 12
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end i_rx rx Input 1
add_interface_port conduit_end o_tx tx Output 1
add_interface_port conduit_end q q Output 8

