# TCL File Generated by Component Editor 17.0
# Wed Mar 30 22:26:15 EEST 2022
# DO NOT MODIFY


# 
# subservient_coprocessor "subservient_coprocessor" v1.0
#  2022.03.30.22:26:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module subservient_coprocessor
# 
set_module_property DESCRIPTION ""
set_module_property NAME subservient_coprocessor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME subservient_coprocessor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL subservient_wrapped_av_wrapped
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ff_ram.v VERILOG PATH ip/serv_uart/rtl/ff_ram.v
add_fileset_file serv_alu.v VERILOG PATH ip/serv_uart/rtl/serv_alu.v
add_fileset_file serv_bufreg.v VERILOG PATH ip/serv_uart/rtl/serv_bufreg.v
add_fileset_file serv_csr.v VERILOG PATH ip/serv_uart/rtl/serv_csr.v
add_fileset_file serv_ctrl.v VERILOG PATH ip/serv_uart/rtl/serv_ctrl.v
add_fileset_file serv_decode.v VERILOG PATH ip/serv_uart/rtl/serv_decode.v
add_fileset_file serv_immdec.v VERILOG PATH ip/serv_uart/rtl/serv_immdec.v
add_fileset_file serv_mem_if.v VERILOG PATH ip/serv_uart/rtl/serv_mem_if.v
add_fileset_file serv_rf_if.v VERILOG PATH ip/serv_uart/rtl/serv_rf_if.v
add_fileset_file serv_rf_ram.v VERILOG PATH ip/serv_uart/rtl/serv_rf_ram.v
add_fileset_file serv_rf_ram_if.v VERILOG PATH ip/serv_uart/rtl/serv_rf_ram_if.v
add_fileset_file serv_rf_top.v VERILOG PATH ip/serv_uart/rtl/serv_rf_top.v
add_fileset_file serv_state.v VERILOG PATH ip/serv_uart/rtl/serv_state.v
add_fileset_file serv_top.v VERILOG PATH ip/serv_uart/rtl/serv_top.v
add_fileset_file servant_timer.v VERILOG PATH ip/serv_uart/rtl/servant_timer.v
add_fileset_file serving.v VERILOG PATH ip/serv_uart/rtl/serving.v
add_fileset_file serving_arbiter.v VERILOG PATH ip/serv_uart/rtl/serving_arbiter.v
add_fileset_file serving_mux.v VERILOG PATH ip/serv_uart/rtl/serving_mux.v
add_fileset_file serving_ram.v VERILOG PATH ip/serv_uart/rtl/serving_ram.v
add_fileset_file subservient.v VERILOG PATH ip/serv_uart/rtl/subservient.v
add_fileset_file subservient_core.v VERILOG PATH ip/serv_uart/rtl/subservient_core.v
add_fileset_file subservient_debug_switch.v VERILOG PATH ip/serv_uart/rtl/subservient_debug_switch.v
add_fileset_file subservient_gpio.v VERILOG PATH ip/serv_uart/rtl/subservient_gpio.v
add_fileset_file subservient_ram.v VERILOG PATH ip/serv_uart/rtl/subservient_ram.v
add_fileset_file subservient_rf_ram_if.v VERILOG PATH ip/serv_uart/rtl/subservient_rf_ram_if.v
add_fileset_file subservient_wrapped.v VERILOG PATH ip/serv_uart/rtl/subservient_wrapped.v
add_fileset_file subservient_wrapped_av_wrapped.v VERILOG PATH ip/serv_uart/rtl/subservient_wrapped_av_wrapped.v TOP_LEVEL_FILE
add_fileset_file uart.v VERILOG PATH ip/serv_uart/rtl/uart.v
add_fileset_file uart_rx.v VERILOG PATH ip/serv_uart/rtl/uart_rx.v
add_fileset_file uart_tx.v VERILOG PATH ip/serv_uart/rtl/uart_tx.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL subservient_wrapped_av_wrapped
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file subservient_alone_tb.v VERILOG PATH ip/serv_uart/bench/subservient_alone_tb.v
add_fileset_file subservient_wrapped_av_wrapped_tb.v VERILOG PATH ip/serv_uart/bench/subservient_wrapped_av_wrapped_tb.v
add_fileset_file subservient_wrapped_tb.v VERILOG PATH ip/serv_uart/bench/subservient_wrapped_tb.v
add_fileset_file uart_tb.v VERILOG PATH ip/serv_uart/bench/uart_tb.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point ss0
# 
add_interface ss0 avalon end
set_interface_property ss0 addressUnits WORDS
set_interface_property ss0 associatedClock clock
set_interface_property ss0 associatedReset reset
set_interface_property ss0 bitsPerSymbol 8
set_interface_property ss0 burstOnBurstBoundariesOnly false
set_interface_property ss0 burstcountUnits WORDS
set_interface_property ss0 explicitAddressSpan 0
set_interface_property ss0 holdTime 0
set_interface_property ss0 linewrapBursts false
set_interface_property ss0 maximumPendingReadTransactions 0
set_interface_property ss0 maximumPendingWriteTransactions 0
set_interface_property ss0 readLatency 0
set_interface_property ss0 readWaitStates 0
set_interface_property ss0 readWaitTime 0
set_interface_property ss0 setupTime 0
set_interface_property ss0 timingUnits Cycles
set_interface_property ss0 writeWaitTime 0
set_interface_property ss0 ENABLED true
set_interface_property ss0 EXPORT_OF ""
set_interface_property ss0 PORT_NAME_MAP ""
set_interface_property ss0 CMSIS_SVD_VARIABLES ""
set_interface_property ss0 SVD_ADDRESS_GROUP ""

add_interface_port ss0 address address Input 13
add_interface_port ss0 chipselect chipselect Input 1
add_interface_port ss0 write_n write_n Input 1
add_interface_port ss0 writedata writedata Input 32
add_interface_port ss0 readdata readdata Output 32
set_interface_assignment ss0 embeddedsw.configuration.isFlash 0
set_interface_assignment ss0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ss0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ss0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point exported
# 
add_interface exported conduit end
set_interface_property exported associatedClock clock
set_interface_property exported associatedReset reset
set_interface_property exported ENABLED true
set_interface_property exported EXPORT_OF ""
set_interface_property exported PORT_NAME_MAP ""
set_interface_property exported CMSIS_SVD_VARIABLES ""
set_interface_property exported SVD_ADDRESS_GROUP ""

add_interface_port exported q gpio Output 38
add_interface_port exported debug_mode_i debug_mode Input 1
add_interface_port exported i_rx uart_rx Input 1
add_interface_port exported o_tx uart_tx Output 1
add_interface_port exported wb_dbg_ack ignore_me Output 1

