#include "utility.h"
#include "memory_map.h"


void entry_point () __attribute__((section(".entry_point")));

void entry_point () {
    //100MHz/115200Baudrate = 868. Clock generated by toggling. Hence half of it 434 is prescalar
    PRESCALAR = 434;

    //  00->5 bits of data|00->no parity  |0->1 stop bits
    //  01->6 bits of data|01->even parity|1->2 stop bits
    //  10->7 bits of data|10->no parity  |
    //  11->8 bits of data|11->odd parity |
    UART_CFG = 0b11000; // 8 bits, no parity, 1bit stop

    TX_DATA = 0b10101010; // random data
    TX_SEND = 1;
    while(!RX_READY){
        GPIO_0 = 1;
        GPIO_0 = 0;
    }
    GPIO_0 = RX_DATA;
    passed();
    GPIO_1 = 0b010000;
}
